apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
  nodeDisruptionPolicy:
    files:
      - path: /usr/local/bin/egress-steering-reconciler.sh
        actions:
          - type: Restart
            restart:
              serviceName: egress-steering.service
      - path: /etc/egress-steering/egress-steering.conf
        actions:
          - type: Restart
            restart:
              serviceName: egress-steering.service
      - path: /etc/egress-steering/ca.crt
        actions:
          - type: Restart
            restart:
              serviceName: egress-steering.service
      - path: /etc/egress-steering/token
        actions:
          - type: Restart
            restart:
              serviceName: egress-steering.service

